name: workflow
on:
  push:
    paths:
      - 'scripts/session_6/hello_world.txt'
  pull_request:
    paths:
      - 'scripts/session_6/hello_world.txt'
jobs:
  call-hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Display Hello World
        run: |
          if [ "$GITHUB_EVENT_NAME" == 'push' ]; then
            cat scripts/session_6/hello_world.txt
          elif [ "$GITHUB_EVENT_NAME" == 'pull_request' ]; then
            cat scripts/session_6/pull_request_test.txt
          else
            echo "No valid event found."
            exit 1
          fi